name: Run Tests and Close PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-and-close:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Close PR using PAT
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "✅ All tests passed. Closing PR #$PR_NUMBER..."
          gh pr close "$PR_NUMBER" --comment "✅ All test cases passed. PR closed automatically."
